// Regenerates sitemap.xml from every indexable index.html in the repo.
//
//   node scripts/build-sitemap.mjs
//
// lastmod = the file's last git commit date (today if uncommitted).
// Pages with <meta name="robots" content="noindex..."> are skipped.

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://www.nationwidehaul.com';
const SKIP = new Set(['node_modules', '.git', 'scripts', 'api', 'supabase', '.vercel']);
const today = new Date().toISOString().slice(0, 10);

async function walk(dir, out = []) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || SKIP.has(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) await walk(p, out);
    else if (e.name === 'index.html') out.push(p);
  }
  return out;
}

const lastmod = (file) => {
  const dirty = execFileSync('git', ['status', '--porcelain', '--', file], { cwd: root }).toString().trim();
  if (dirty) return today;
  return execFileSync('git', ['log', '-1', '--format=%cs', '--', file], { cwd: root }).toString().trim() || today;
};

const priority = (u) => u === '/' ? '1.0'
  : /^\/(trailers|financing|lease|locations)\//.test(u) ? '0.9'
  : /^\/(manufacturers|resources)\//.test(u) ? '0.8'
  : u.startsWith('/legal/') ? '0.3' : '0.7';

const urls = [];
for (const file of await walk(root)) {
  const html = await readFile(file, 'utf8');
  if (/<meta name="robots" content="noindex/i.test(html)) continue;
  const rel = path.relative(root, path.dirname(file)).split(path.sep).join('/');
  const u = rel ? `/${rel}/` : '/';
  urls.push({ u, lastmod: lastmod(file) });
}
urls.sort((a, b) => (a.u === '/' ? -1 : b.u === '/' ? 1 : a.u.localeCompare(b.u)));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs — do not edit by hand -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(({ u, lastmod }) => `  <url>
    <loc>${SITE}${u}</loc>
    <lastmod>${lastmod}</lastmod>
    <priority>${priority(u)}</priority>
  </url>`).join('\n')}
</urlset>
`;
await writeFile(path.join(root, 'sitemap.xml'), xml);
console.log(`sitemap.xml: ${urls.length} URLs`);
